### ISSUE TITLE
Does not work with PHP 7

### ISSUE THREAD

**Issue by wowawebdesign** [nimius/workshops#1]
Seems the extensions does not work with PHP 7. I got an exception in the frontend.

(TYPO3 7.6.9, PHP 7.0.0 on a Mac with MampPro).
Works with PHP 5.6.10.

![workshops-exception](https://cloud.githubusercontent.com/assets/343511/16225804/c74f8438-37a8-11e6-9953-09e67d2c665f.png)

**Comment by pduersteler** [comment]
Thanks for reporting!

The error above is fixed on development branch in commit 8c84195, but the extension is not tested thoroughly in php7.0, therefore leaving this issue open.

**Comment by pduersteler** [comment]
The link view helper has been adapted to work properly with php7
